services:
  # Backend API Service
  - type: web
    name: smartshop-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8000
      - key: CORS_ORIGINS
        value: '["https://smartshop-frontend.onrender.com", "http://localhost:3000", "http://localhost:5173"]'

  # Frontend Static Site
  - type: web
    name: smartshop-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm ci --only=production && npm run build
    staticPublishPath: frontend/dist
    healthCheckPath: /
    envVars:
      - key: VITE_API_URL
        value: https://smartshop-backend.onrender.com
      - key: NODE_VERSION
        value: 20.19.0 